import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TranslationProvider } from './providers/TranslationProvider';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Autodienst24.at",
  description: "Generated by nikollgjokaj",
  keywords: "Autodienst, Auto, Service, Reparatur, Österreich",
  authors: [{ name: "Nikoll Gjokaj", url: "https://www.autodienst24.at" }],
  openGraph: {
    title: "Autodienst24.at",
    description: "Ihr zuverlässiger Partner für Autoreparaturen in Österreich.",
    type: "website",
    url: "https://www.autodienst24.at",
    images: ["https://www.autodienst24.at/og-image.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    site: "@IhrTwitterHandle",
    title: "Autodienst24.at",
    description: "Ihr zuverlässiger Partner für Autoreparaturen in Österreich.",
    images: ["https://www.autodienst24.at/og-image.jpg"],
  },
  robots: "index, follow",
};

export const viewport = "width=device-width, initial-scale=1";

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TranslationProvider>
          {children}
        </TranslationProvider>
      </body>
    </html>
  );
};

export default RootLayout;
