import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TranslationProvider } from './providers/TranslationProvider';
import { ThemeProvider } from './providers/ThemeProvider';
//import CookieBanner from './components/CookieConsent/CookieBanner';

export const metadata: Metadata = {
  title: "Autodienst24.at",
  description: "Generated by nikollgjokaj",
  keywords: "Autodienst, Auto, Service, Reparatur, Österreich",
  authors: [{ name: "Nikoll Gjokaj", url: "https://www.autodienst24.at" }],
  openGraph: {
    title: "Autodienst24.at",
    description: "Ihr zuverlässiger Partner für Autoreparaturen in Österreich.",
    type: "website",
    url: "https://www.autodienst24.at",
    images: ["https://www.autodienst24.at/og-image.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    site: "@IhrTwitterHandle",
    title: "Autodienst24.at",
    description: "Ihr zuverlässiger Partner für Autoreparaturen in Österreich.",
    images: ["https://www.autodienst24.at/og-image.jpg"],
  },
  robots: "index, follow",
};

export const viewport = "width=device-width, initial-scale=1";

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html>
      <body>
        <ThemeProvider>
          <TranslationProvider>
            {children}
          </TranslationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
