import type { Metadata } from "next";
import "./globals.css";
import { ClientLayout } from './components/ClientLayout';

export const metadata: Metadata = {
  title: "Autodienst24.at",
  description: "Generated by nikollgjokaj",
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/apple-icon.png',
    other: {
      rel: 'apple-touch-icon',
      url: '/apple-icon.png',
    },
  },
  keywords: "Autodienst, Auto, Service, Reparatur, Österreich",
  authors: [{ name: "Nikoll Gjokaj", url: "https://www.autodienst24.at" }],
  openGraph: {
    title: "Autodienst24.at",
    description: "Ihr zuverlässiger Partner für Autoreparaturen in Österreich.",
    type: "website",
    url: "https://www.autodienst24.at",
    images: ["https://www.autodienst24.at/og-image.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    site: "@IhrTwitterHandle",
    title: "Autodienst24.at",
    description: "Ihr zuverlässiger Partner für Autoreparaturen in Österreich.",
    images: ["https://www.autodienst24.at/og-image.jpg"],
  },
  robots: "index, follow",
};

export const viewport = "width=device-width, initial-scale=1";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
